add editor plugin code
ethereum/remix-plugin pull request #238
Opened 2020-09-07 09:44 UTC by 0mkara

2020-09-07 10:06 UTC, GrandSchtroumpf requested changes

2020-09-07 10:06 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    const fileUri = window.activeTextEditor ? window.activeTextEditor.document.uri : undefined; // TODO: we might want to supply path to addAnnotation function
Yes : 
```typescript
private getEditor(filePath?: string) {
  return path
    ? editors.find(editor => editor.document.uri.path === Uri.parse(filePath).path)
    : window.activeTextEditor
}
addAnnotation(annotation: Annotation, filePath?: string) {
  const editor = this.getEditor(filePath);
  if (editor) {
    ...
  }
}
```

2020-09-07 10:06 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    let canonicalFile = fileUri.toString();
Why no `uri.fsPath` ?

2020-09-07 10:06 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    let diagnosticMap: Map<string, Diagnostic[]> = new Map();
use const (same for all below)

2020-09-07 10:06 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    let svrt: DiagnosticSeverity = 0;
Better to have a mapping : 
```typescript
const diagnosticSeverity: Record<string, DiagnosticSeverity> = {
  'error': DiagnosticSeverity.Error,
  'warning': DiagnosticSeverity.Warning,
  ...
}
...
const severity = diagnosticSeverity[annotation.type];
```

2020-09-14 15:24 UTC, GrandSchtroumpf requested changes

2020-09-14 15:24 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +const profile = {
You should be able to import it from @remixproject/plugin-api too. Check how I did it in filemanager

2020-09-14 15:24 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +export default class EditorPlugin extends CommandPlugin {
Don't use default

2020-09-14 15:24 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +      this.diagnosticCollection.set(Uri.parse(file), diags);
Are you sure Uri.parse is working ? From my experience you need to use Uri.file instead.

2020-09-14 15:24 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    return;
No need to add return.

2020-09-28 07:51 UTC, GrandSchtroumpf requested changes

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    // @ts-ignore
Why do you need to ignore here ?

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +      return editor.setDecorations(this.decoration, [newDecoration]);
If `setDecorations` returns void, then don't return it at all. Else update the output type of the method.

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +  async discardHighlightAt(line: number, filePath: string): Promise<void> {
Remove the params and add a comment : 
```typescript
/**
 * Alisas of  discardHighlight
 * Required to match the standard interface of editor
 */
```

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    return filePath ? editors.find(editor => editor.document.uri.path === Uri.parse(filePath).path) : window.activeTextEditor
Is Uri.parse working on Windows ?

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +  private getEditor(filePath?: string): TextEditor {
This method doesn't need to be part of the class (doesn't use `this` and is not exposed). Put it outside of the class declaration as a standalone function.

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    const diagnosticMap: Map<string, Diagnostic[]> = new Map();
I don't see the point of using a Map structure if you're using a string as key. `Map` structure is useful when you want to use a reference (object for example) as a key. 
Using a Javascript Object structure (Record) would be lighter I think.

2020-09-28 07:51 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    const diagnostics = diagnosticMap.get(canonicalFile) ? diagnosticMap.get(canonicalFile) : [];
How is it possible that you get a diagnostic from the `diagnosticMap` ? You just initialize the map two lines above and you don't mutate it in-between.
The way I see it you should have : 
```typescript
const editor = this.getEditor(filePath);
const path = editor.document.uri.fsPath;
const range = new Range(annotation.row - 1, annotation.column, annotation.row - 1, annotation.column);
const severity = diagnosticSeverity[annotation.type];
const diagnostic = new Diagnostic(range, annotation.text, severity);
this.diagnosticCollection?.set(Uri.file(path), [ diagnostic ]);
```

2020-09-28 08:02 UTC, 0mkara commented on packages/engine/vscode/src/lib/editor.ts
> +    return filePath ? editors.find(editor => editor.document.uri.path === Uri.parse(filePath).path) : window.activeTextEditor
I am unable to check that.

2020-09-28 09:54 UTC, GrandSchtroumpf approved these changes

2020-09-28 09:54 UTC, GrandSchtroumpf commented on README.md
> +## Build `engine-vscode`
Better: 
```typescript
## Build a specific project
npx nx build ${projectName} --with-deps

Example for engine-vscode :
npx nx build engine-vscode --with-deps
```

```

2020-09-28 09:54 UTC, GrandSchtroumpf commented on packages/engine/vscode/src/lib/editor.ts
> +    const diagnostic: Diagnostic = new Diagnostic(range, annotation.text, severity);
You shouldn't need to force type it to `Diagnostic`. Let typescript do the job for you when possible ;)

2020-09-28 11:06 UTC, closed without merging